language: python
python:
- '3.6'
- '3.7'
- '3.8'
os: linux
arch:
- arm64
- ppc641e
- s390x
script:
- pytest --cov=./
install:
- pip install -r requirements.txt
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: Pg8kJD/F0+v2NW9qbBmjwFgq3AT4p2rw7CcuZQDpKVfgOqDBUGYG/IQewnoGxu7/yrwkKhZgze6z4d3SS4XEn89f9qfOFGvSRFpMDV8F88tSwq5sNKRutLTOVnn4q4QlTAsG1XOK3KZL7ByKj6igS16/5RkmY5k3oXbt2IqWnn2m95Z9FLrqyt0eNd3kRVsGbViJunpbQXCvizC9s2bwJ8gPlWgUY+zpIJPawkc+tpyeq6crIvyTQLHjGCSlX28ZDCkTJNsWlsakYyLBcqGpXd6vZ0FJqc394xMYzB7/V3R+L32yyMNYFbJrpxwCL+29rcyGI0KMuXoxwJE7q4wFZax0CkkPdkTOWt5MCswCBPuVAGIq4Tj8ySgDV1nbFYfTg2WSb931pWR2tlevJFkxYcE2KVLCWDvtiiislvp7+OAzy2LpaK4MIYepBWCJ43BKg4Qt7BMZVbAEz0SKNspZe91W5ywRm91qMw5yLV3xxYyaVhCgWmSwJ4cufbJpbIUtCHn5mofXpy2bUHi2L6pn/YPu/xSgA/HHvo4ZcVyVIjW0YN//UDrLLz5iXSxZKI94ltd9sspA7wBua481AY4NOiw2eVSibgt0N9DB9jcZiLLi2Ibis8oONM47UXyFro36cOH6eQWk3VfMiV5jum5IyRcQlQYDl5uDzh7d0lhRNOM=
  - secure: JipQzKOuXs0v3LisqxDKtq8PqZKoaJbYm0eeJ1YLPlsdRdxGgQySIxmUPr45/R3+pgn0ASak39X44mZj1XxR2UI9siLvsDDk6xnzGthwTtLaZ2F2HzTa6k4UEvw704cCdIiTX9PaGYs4XlaKY9DKoN7pCh5gnjcDKi6slupCmipREIcwniKFelS6ouhtskJvNMZClVMnlybpJr1HhDMncQPC996gBmFQbXSe42bOjA6Rp3HyX/dDhjTyXeU0ygL35lcOft0/4nqaNvURLaTAweYOMr3zFHwhOEUO2hGBkb0uCfUgyWtPD7xVprrCb8kGBN80aXQUfa/e3/Ldvych6DMR65aPXVoBlcqagxsIxlUVTB9XoQMglKfnWFP650HQcp5KdYV+3nDHIZs3vX4nf3HC1ATEP3uMj4hjgdNQHvkeEeWxLQEd5Uscjz/yLGrMEJ07XA650ermf/RmMp5YKvap1l6/r2WIVt6q8Lit6SaHAijlUsy6rW+460V+fA6GeNhh0SoO9HQpF6jjQ/qtYEnjfB3AtZusdDEwxDNpKXjSO1fzx/hKLZHA8fOoE5ehsL+mpC5TfLsCJuUccsNjlhipKopSpaIUT1FyH/rxSEHVGeSetBUVe8fj27024p70Szim5XT+Xz4CjkgKDacjpZWRbaPq+ZFEDigPUCxfwg0=
