language: python
python:
- '3.6'
- '3.7'
- '3.8'
os: linux
arch:
- arm64
- ppc64le
- s390x
script:
- pytest --cov=./
install:
- pip install -r requirements.txt
after_success:
- bash <(curl -s https://codecov.io/bash)

